version: '3'
services:

  wordpress:
    image: wordpress:${WORDPRESS_VERSION:-latest}
#    image: wordpress:php7.3-apache
#    image: wordpress:php7.4-apache
#    image: wordpress:php8.1-apache
#    image: wordpress:5-php8.1-apache
#    image: wordpress:5.8-php8.1-apache
#    image: wordpress:5.8.2-php8.1-apache
#    image: wordpress:5.9-php8.0-apache
#    image: wordpress:5.9-php8.1-apache
#    image: wordpress:beta-5-php7.4-apache
#    image: wordpress:beta-5-php8.1-apache
    container_name: ${COMPOSE_PROJECT_NAME:-wordpress}
    volumes:
      - ./.docker/server/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ${PLUGINS_DATA_DIR:-./volumes/plugins}:/var/www/html/wp-content/plugins
      - ${WORDPRESS_DATA_DIR:-./volumes/wordpress}:/var/www/html
    environment:
      - WORDPRESS_DB_NAME=${COMPOSE_PROJECT_NAME:-wordpress}
      - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX:-wp_}
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST:-mysql}
      - WORDPRESS_DB_USER=${DATABASE_USER:-root}
      - WORDPRESS_DB_PASSWORD=${DATABASE_PASSWORD:-password}
      - WORDPRESS_DEBUG=${WORDPRESS_DEBUG:-true}
    depends_on:
      - mysql
    restart: always
    ports:
        - ${WORDPRESS_SITE_PORT:-80}:80

  mysql:
    image: mariadb:${MARIADB_VERSION:-latest}
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    volumes:
      - ${MYSQL_DATA_DIR:-./volumes/mysql}:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD:-password}
      - MYSQL_USER=${DATABASE_USER:-root}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD:-password}
      - MYSQL_DATABASE=${COMPOSE_PROJECT_NAME:-wordpress}
    restart: always


  phpmyadmin:
     depends_on:
       - mysql
     image: phpmyadmin/phpmyadmin
     restart: always
     ports:
       - ${PMA_PORT:-8080}:80
     environment:
       - PMA_HOST=${WORDPRESS_DB_HOST:-mysql}
       - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD:-password}
